# Generated by Django 2.2.6 on 2019-10-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philipp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstable',
            name='laptop_access',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesstable',
            name='laptop_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesstable',
            name='laptop_status',
            field=models.CharField(default='in storage', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesstable',
            name='terminal_access',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesstable',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
